Propose idea page
404-Hub/FRONTEND pull request #1
Opened 2023-12-05 08:49 UTC by sensaur

Add add routing to desktop/mobile navbar on tabs click &
add desktop version for propose idea page with stepper and collecting data from user.

2023-12-05 20:44 UTC, tomfordrumm requested changes
В целом все хорошо, но есть несколько моментов, которые я описал в комментах.

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +  Далее: commonContainedStyle,
Давай избегать русских слов в ключах массивов :) Переделай пожалуйста на их англоязычные аналоги

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +          Давай подытожим 🙂
Сорри, забыл про это написать в задаче, давай для текстов использовать i18n чтобы мы имели возможность быстро перевести весь сервис на другой язык

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +    Далее: handleNextClick,
Здесь тоже давай русский заменим на англоязычные аналоги

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +              onClick={buttonActions['Изменить данные']}
Вот тут поправить после изменения ключей

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +          {userInputs['Опишите, что нужно сделать']}
Вот тут поправить после изменения полей

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +              onChange={(e) => handleInputChange(currentStep.labelTitle, e.target.value)}
Вот тут вместо step Label давай передавать field name (который нужно будет добавит в stepData.json) 

Маппинг такой: 

title -> название 
description -> Что нужно сделать?
additional -> Кто ваш клиент

2023-12-05 20:44 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +            <TextField
Возможно ли для description и additional использовать вот этот компонент 
https://mui.com/base-ui/react-textarea-autosize/ ?

2023-12-06 22:09 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +  Далее: commonContainedStyle,
готово, поправил

2023-12-06 22:13 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +          Давай подытожим 🙂
Ага, пока сделал внутри компонента переключатель между русским и английским, надо подумать как оптимальнее настроить на все приложение, достаточно того что идет из коробки некст или допом i18next

2023-12-06 22:13 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +    Далее: handleNextClick,
готово

2023-12-06 22:13 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +              onClick={buttonActions['Изменить данные']}
готово

2023-12-06 22:13 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +          {userInputs['Опишите, что нужно сделать']}
готово

2023-12-06 22:13 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +              onChange={(e) => handleInputChange(currentStep.labelTitle, e.target.value)}
готово

2023-12-06 22:17 UTC, sensaur commented on src/app/propose-idea/page.tsx
> +            <TextField
я попробовал Textarea Autosize но поехали стили и быстро не смог сделать визуальное оформление похожее на TextField. Если нужна многострочность в инпуте то у TextField есть свойство multiline которое это позволяет, посмотри пж в текущей версии покрывает ли это то что нужно, если нет - вернемся к Textarea Autosize

2023-12-10 16:27 UTC, tomfordrumm commented on src/app/propose-idea/page.tsx
> +          Давай подытожим 🙂
Не, давай сразу next-i18n прикручивать :)

2023-12-16 22:14 UTC, sensaur commented
Подрубил пакет next-intl + к нему конфиги i18nMiddleware, i18n
Перенес страницы вложив в папку [locale] 
Обернул корневой компонент в LocaleProvider чтобы класть локаль в контекст и юзать ее при рендеринге страниц на клиенте
Сделал мультиязычной страницу my-task - в зависимости от локали вывод контента через t
http://localhost:3000/ru/my-tasks
http://localhost:3000/en/my-tasks

2023-12-29 12:49 UTC, closed without merging